chat/urls.py
from django.urls import path

urlpatterns = []

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/",include("account.urls")),
    path("",include("post.urls")),
    path("chat/",include("chat.urls")),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views


app_name = "post"
urlpatterns = [
        path("",views.home,name="home"),
        path("post/",views.post,name="post"),
        path("follows/",views.follow,name="follow"),
        path("profile/<uuid:user_id>/",views.profile,name="user_profile"),
        path("follows/addfollow/",views.addfollow,name="addfollow"),
        path("notification/",views.notification,name="notification"),
        path("like/",views.like,name="like"),
        ]

post/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()



class Notification(models.Model):
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING,related_name="sender")
    receiver = models.ForeignKey(User,on_delete=models.DO_NOTHING,related_name="receiver")
    content = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.content



class Post(models.Model):
    post_owner = models.ForeignKey(User,on_delete=models.CASCADE,related_name="posts")
    post_image = models.ImageField(upload_to="post_image",blank=True,null=True)
    caption = models.CharField(max_length=3000,blank=True,null=True)
    like = models.ManyToManyField(User)
    date_posted = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-date_posted"]

    def __str__(self):
        return self.post_owner.username



class Comment(models.Model):
    commentter = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name="comments")
    comment = models.TextField()
    date_commented = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-date_commented"]

    def __str__(self):
        return self.post.caption



class Reply(models.Model):
    replier = models.ForeignKey(User,on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment,on_delete=models.CASCADE,related_name="replies")
    reply = models.CharField(max_length=200)
    date_replied = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-date_replied"]
        verbose_name_plural = "Replies"

    def __str__(self):
        return self.reply

post/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Post,Notification
from django.http import HttpRequest,JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.views.decorators.csrf import csrf_exempt


User= get_user_model()

@login_required
def home(request:HttpRequest):
    posts = Post.objects.all()
    context = {"posts":posts}

    return render(request,"post/home.html",context)

@login_required
def post(request:HttpRequest):
    if request.method == "POST":
        caption = request.POST.get("caption")
        post_image = request.FILES.get("post_image")
        print(post_image)
        Post.objects.create(
                post_owner = request.user,
                caption = caption,
                post_image = post_image,
                )
        return redirect("post:home")
    return render(request,"post/post.html")


#this view brings all avialable user that can be followed
@login_required
def follow(request:HttpRequest):
    if request.method == "POST":
        search = request.POST.get("search")
        friends = User.objects.filter(username__icontains=search)

    else:
        friends = User.objects.exclude(username=request.user.username)
    context = {"follows":friends}
    return render(request,"post/follow.html",context)


@login_required
def profile(request:HttpRequest,user_id):
    user = get_object_or_404(User, id=user_id)
    return render(request,"post/profile.html",{"user":user})


#follows a user once the follow button is clicked 
@csrf_exempt
def addfollow(request:HttpRequest):
    if request.method == "POST":
        u_id = request.POST.get("id")
        status = request.POST.get("status")

        following = get_object_or_404(User, id=u_id)
        current_user = request.user

        # mutual followers logic
        mutual_friends = []
        for follower in following.followed_by.all():
            if follower in current_user.followed_by.all():
                mutual_friends.append(follower)

        if status == "follow":
            current_user.follows.add(following)

            Notification.objects.create(
                user=current_user,
                receiver=following,
                content=f"{current_user} just followed you")

            current_user.save()
            return JsonResponse({"follow_num":following.followed_by.count()})

        elif status == "unfollow":
            current_user.follows.remove(following)

            Notification.objects.create(
                user=current_user,
                receiver=following,
                content=f"{current_user} just Unfollowed you")

            current_user.save()
            return JsonResponse({"follow_num":following.followed_by.count()})


@login_required
def notification(request:HttpRequest):
    notifications = Notification.objects.filter(receiver=request.user)
    context = {"notifications":notifications}
    return render(request,"post/notification.html",context)

@csrf_exempt
def like(request:HttpRequest) -> JsonResponse:
    if request.method == "POST":
        p_id = request.POST.get("id")
        print(p_id)

        post = get_object_or_404(Post,id=int(p_id))

        if request.user not in post.like.all():
            post.like.add(request.user)
        else:
            post.like.remove(request.user)

        return JsonResponse({"like":post.like.count()})

post/templates/post/follow.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/follow.css' %}">
    <title>Follow</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>
<body>
    <nav>
        <h3>Follow</h3>
    </nav>

    <div class="search">

        <form method="post">

          {% csrf_token %}
            <input type="search" name="search" placeholder="search">
            <button style="display:none;">search</button>
        </form>
    </div>
    <main>
      {% for follow in follows %}
        <div class="user-card">
            <div class="user-profile">
                <a href="{% url 'post:user_profile' follow.id %}">
                    <img src="{{ follow.profile_pic}}" alt="">
                </a>
            </div>
            <div class="follow-btn-cont">
                <h3 class="username">{{ follow.username }}<i class="bi bi-patch-check-fill"></i></h3>
                <div class="followers"><span class="followerspan">{{ follow.followed_by.count }}</span> Followers</div> 
                {% if follow not in request.user.follows.all %}
                <button class="follow followbtn" value="follow" data-id="{{ follow.id }}"><i class="bi bi-person-add"></i></button>
                {% elif follow in request.user.follows.all %}
                 <button class="follow followbtn" value="unfollow" data-id="{{ follow.id }}">Following</button>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </main>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">

    </script>

    <script src="{% static 'js/follow.js' %}"></script>
</body>
</html>

post/templates/post/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <title>Document</title>
  </head>
  <body>
    <nav class="mobile-nav">
        <a href="{% url 'post:user_profile' request.user.id %}">
          <div class="profile">
            <img src="{{ request.user.profile_pic }}" alt="" />
          </div>
        </a>

      <h2>Feed</h2>

      <div class="notifications">
        <a href="{% url 'post:notification' %}">
          <i class="bi bi-bell"></i>
        </a>
        <span class="notification-number">{{ notification.count }}</span>
      </div>
    </nav>

    <!-- Desktop nav -->
    <nav class="desktop-nav">
      <div class="logo">
        <img src="./Assets/Images/20240102_013013.png" alt="" />
      </div>
      <h2>Feed</h2>

      <div class="icon-nav-links">
        <a href="./index.html">
          <i class="bi bi-house"></i>
        </a>
        <a href="./Assets/Pages/chats.html">
          <i class="bi bi-chat"></i>
        </a>
        <a href="./Assets/Pages/notifications.html">
          <i class="bi bi-bell"></i>
        </a>
        <a href="./Assets/Pages/settings.html">
          <i class="bi bi-gear"></i>
        </a>
      </div>
    </nav>

    <main>
      <div class="profile-scroll">
        <div class="story-cont">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="55"
            height="55"
            fill="purple"
            class="bi bi-plus-circle-fill"
            viewBox="0 0 16 16"
          >
            <path
              d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3z"
            />
          </svg>
          <div class="name">
            <h4>Add to story</h4>
          </div>
        </div>

        <div class="story-cont">
          <div class="story-indicator">
            <div class="profile">
              <a href="">
                <img src="./Assets/Images/Rectangle 3 (2).png" alt="" />
              </a>
            </div>
          </div>
          <div class="name">
            <h4>Jay huskins Ojomakpene</h4>
          </div>
        </div>

        <div class="story-cont">
          <div class="story-indicator">
            <div class="profile">
              <a href="">
                <img src="./Assets/Images/Rectangle 3 (3).png" alt="" />
              </a>
            </div>
          </div>
          <div class="name">
            <h4>Martin Luthur</h4>
          </div>
        </div>

        <div class="story-cont">
          <div class="story-indicator">
            <div class="profile">
              <a href="">
                <img src="./Assets/Images/Rectangle 3 (3).png" alt="" />
              </a>
            </div>
          </div>
          <div class="name">
            <h4>Harry Maguire</h4>
          </div>
        </div>

        <div class="story-cont">
          <div class="story-indicator">
            <div class="profile">
              <a href="">
                <img src="./Assets/Images/Rectangle 3.png" alt="" />
              </a>
            </div>
          </div>
          <div class="name">
            <h4>Donald Trump</h4>
          </div>
        </div>

        <div class="story-cont">
          <div class="story-indicator">
            <div class="profile">
              <a href="">
                <img src="./Assets/Images/Rectangle 3 (1).png" alt="" />
              </a>
            </div>
          </div>
          <div class="name">
            <h4>Steve Jobs</h4>
          </div>
        </div>

        <div class="story-cont">
          <div class="story-indicator">
            <div class="profile">
              <a href="">
                <img src="./Assets/Images/Rectangle 3 (2).png" alt="" />
              </a>
            </div>
          </div>
          <div class="name">
            <h4>Samuel Egin</h4>
          </div>
        </div>
      </div>

      <div class="main-feed">
        {% for post in posts %}
        {% if post.post_owner in request.user.follows.all %}
        <div class="post-cont">
          <div class="post-header">
            <div class="header-profile">
              <div class="story-indicator">
                <a href="{% url 'post:user_profile' post.post_owner.id %}">
                  <div class="profile">
                    <img src="{{ post.post_owner.profile_pic }}" alt="" />
                  </div>
                </a>
              </div>

              <div class="info">
                <h2 class="post-author">{{ post.post_owner.username }}</h2>
                <p class="post-timestamp">{{ post.date_posted }}</p>
              </div>
            </div>
            <div class="others">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                fill="currentColor"
                class="bi-three-dots-vertical"
                viewBox="0 0 16 16"
              >
                <path
                  d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"
                />
              </svg>
            </div>

            <div class="others-div">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="25"
                height="25"
                fill="currentColor"
                class="bi-x"
                viewBox="0 0 16 16"
              >
                <path
                  d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"
                />
              </svg>
              <a href="">Copy Link</a>
              <a href="">Don't show me this</a>
              <a href="">Save Post</a>
              <a href="">Share post</a>
            </div>
          </div>

          <p class="caption">{{ post.caption }}</p>

          <div class="post-img" style="margin-bottom:2em;">
            <img src="" alt="" />
          </div>

          <div class="complements">
            <button class="like" style="border:none; outline:none; background:none;" data-id="{{ post.id }}">
              <i class="bi bi-heart"></i>
            </button>
            <p class="likeNum">{{ post.like.count}}</p>
            <a href="">
              <i class="bi bi-chat"></i>
            </a>
          </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </main>

    <div class="footer-nav">
      <a href="{% url 'post:home' %}">
        <i class="bi bi-house"></i>
      </a>

      <a href="./Assets/Pages/chats.html">
        <i class="bi bi-chat"></i>
      </a>

      <a href="./Assets/Pages/settings.html">
        <i class="bi bi-gear"></i>
      </a>

      <a href="{% url 'post:follow' %}">
        <i class="bi bi-person-add"></i>
      </a>
    </div>

    <a href="{% url 'post:post' %}" class="open-file">
      <i class="bi bi-plus-circle-fill"></i>
    </a>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

post/templates/post/notification.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Notifications</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <link rel="stylesheet" href="{% static 'css/notification.css' %}" />
  </head>
  <body>
    <header class="header">
      <a href="{% url 'post:home' %}">
        <i class="bi bi-arrow-left-circle"></i>
      </a>
      <h2>Notifications</h2>
    </header>

    <main>
      {% for notification in notifications %}
      <a href="">
        <div class="notification">
          <h4 class="notification-time">{{ notification.date }}</h4>
          <div class="notification-body">
            <span class="notification-actor">{{ notification.user.username }}</span>
            <p class="notification-action">{{ notification.content }}</p>
          </div>
        </div>
      </a>
      {% endfor %}
    </main>
  </body>
</html>

post/templates/post/post.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <title>Post</title>
    <link rel="stylesheet" href="{% static 'css/post.css' %}" />
  </head>
  <body>
    <header>
      <div class="return">
        <a href="{% url 'post:home' %}">
          <i class="bi bi-chevron-left"></i>
        </a>
        <span>Create a new post</span>
      </div>
      
    </header>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
    <main>
        <textarea
          name="caption"
          id=""
          cols="30"
          rows="10"
          placeholder="Write something......"
          required
        ></textarea>
    </main>
    <footer>
      <input type="file" name="post_image" id="fileInput" style="display:none;">
      <div class="upload-images" onclick="document.getElementById('fileInput').click()">
        <div class="img-svg">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="20"
            height="20"
            fill="purple"
            class="bi bi-file-image"
            viewBox="0 0 16 16"
          >
            <path d="M8.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0" />
            <path
              d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v8l-2.083-2.083a.5.5 0 0 0-.76.063L8 11 5.835 9.7a.5.5 0 0 0-.611.076L3 12z"
            />
          </svg>
        </div>
        <div class="desc">upload</div>
      </div>
      <div class="make-post-cont">
        <div class="make-post">
          <button style="border:none; ">
          <div class="post-svg">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              fill="white"
              class="bi bi-send-fill"
              viewBox="0 0 16 16"
            >
              <path
                d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 3.178 4.995.002.002.26.41a.5.5 0 0 0 .886-.083l6-15Zm-1.833 1.89L6.637 10.07l-.215-.338a.5.5 0 0 0-.154-.154l-.338-.215 7.494-7.494 1.178-.471-.47 1.178Z"
              />
            </svg>
          </div>
          </button>
        </div>
        <div class="desc">Post</div>
      </div>

      <div class="tag-friends">
        <div class="tag-svg">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="20"
            height="20"
            fill="purple"
            class="bi bi-people-fill"
            viewBox="0 0 16 16"
          >
            <path
              d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"
            />
          </svg>
        </div>
        <div class="desc">Tag</div>
      </div>
    </footer>
    </form>
  </body>
</html>

post/templates/post/profile.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>User's Profile</title>
        <link rel="stylesheet" href="{% static 'css/profile.css' %}" />
    </head>
    <body>
        <div class="gen-cont">
            <div class="nav">
                <div class="back">
                    <a href="">
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="32"
                            height="32"
                            fill="white"
                            class="bi bi-arrow-left"
                            viewBox="0 0 16 16"
                        >
                            <path
                                fill-rule="evenodd"
                                d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"
                            />
                        </svg>
                    </a>
                </div>

                <div class="camera">
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="32"
                        height="32"
                        fill="white"
                        class="bi bi-camera"
                        viewBox="0 0 16 16"
                    >
                        <path
                            d="M15 12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h1.172a3 3 0 0 0 2.12-.879l.83-.828A1 1 0 0 1 6.827 3h2.344a1 1 0 0 1 .707.293l.828.828A3 3 0 0 0 12.828 5H14a1 1 0 0 1 1 1v6zM2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2z"
                        />
                        <path
                            d="M8 11a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5zm0 1a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM3 6.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"
                        />
                    </svg>
                </div>
            </div>

            <div class="cover-photo">
                <img src="../Images/space-g0a47e3e69_1920.jpg" alt="" />
            </div>

            <div class="profile-content">
                <div class="content-header">
                    <div class="friends">
                        <h4>{{ user.follows.count }}</h4>
                        <p>Following</p>
                    </div>
                    <div class="profile-picture">
                        <img src="{{ user.profile_pic }}" alt="" />
                        <h2>{{ user.username }}</h2>
                    </div>
                    <div class="followers">
                        <h4>{{ user.followed_by.count }}</h4>
                        <p>Followers</p>
                    </div>
                </div>
                <div class="bio">
                    <p>{{ user.bio }}</p>
                </div>
                <div class="f-cont">
                    {% if user not in request.user.follows.all %}
                    <button
                        class="follow followbtn"
                        value="follow"
                        data-id="{{ user.id }}"
                    >
                        Follow
                    </button>
                    {% elif user in request.user.follows.all %}
                    <button
                        class="follow followbtn"
                        value="unfollow"
                        data-id="{{ user.id }}"
                    >
                        Following 
                    </button>
                    {% endif %}

                    <div class="message">
                        <button>Message</button>
                    </div>
                </div>
                <div class="mid-nav">
                    <span class="all">
                        <a href="">All</a>
                    </span>
                    <span class="videos">
                        <a href="">Videos</a>
                    </span>
                    <span class="photos">
                        <a href="">Photos</a>
                    </span>
                </div>
                <div class="img">
                    <a href="">
                        <div class="recent">
                            <img
                                src="../Images/pexels-roman-odintsov-6898856.jpg"
                                alt=""
                            />
                        </div>
                    </a>

                    <a href="">
                        <div class="recent">
                            <img
                                src="../Images/pexels-james-wheeler-1519088.jpg"
                                alt=""
                            />
                        </div>
                    </a>

                    <a href="">
                        <div class="recent">
                            <img
                                src="../Images/space-g0a47e3e69_1920.jpg"
                                alt=""
                            />
                        </div>
                    </a>

                    <a href="">
                        <div class="recent">
                            <img
                                src="../Images/pexels-roberto-nickson-2478248.jpg"
                                alt=""
                            />
                        </div>
                    </a>

                    <a href="">
                        <div class="recent">
                            <img
                                src="../Images/pexels-rodolfo-clix-1036936.jpg"
                                alt=""
                            />
                        </div>
                    </a>

                    <a href="">
                        <div class="recent">
                            <img
                                src="../Images/pexels-roman-odintsov-6898856.jpg"
                                alt=""
                            />
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="{% static 'js/follow.js' %}"></script>
    </body>
</html>